Test ory aothkeeper rock release
cjdcordeiro/oci-factory pull request #15
Opened 2023-05-11 15:28 UTC by natalian98

2023-05-11 15:42 UTC, natalian98 commented
@cjdcordeiro could you re-run the failed cla check?

2023-05-23 09:57 UTC, cjdcordeiro requested changes

2023-05-23 09:57 UTC, cjdcordeiro commented on oci/oathkeeper/image.yaml
> +    edge: 0.40.3
this needs to be either a revision number or a fully-formed channel. So I think you're missing the `_edge` if your goal is to follow the 0.40.3_edge tag you're building

2023-05-23 09:57 UTC, cjdcordeiro commented on oci/oathkeeper/image.yaml
> +    release:
you're missing the canonical track here - `<version>-base`. This is mandatory as all images must have at least that track, for consistency. See https://github.com/canonical/oci-factory#image-trigger-file (`upload[*].release.<track>`)

2023-05-31 14:20 UTC, cjdcordeiro approved these changes
thanks @natalian98.

I had to force rebase this fork and thus why your PR got altered, but the good news is that your build was successful (https://github.com/cjdcordeiro/oci-factory/actions/runs/5056416465/jobs/9236574095?pr=15#step:5:636).

I'm closing this as there's no point merging it to a fork, but you should now feel free to:
1. keep testing other stuff against this fork, or
2. move upstream to canonical/oci-factory 

;)

2023-05-31 14:20 UTC, closed without merging